# Generated by Django 5.2.9 on 2025-12-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_notebook_notebookpdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentembedding',
            name='page_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
