# Generated by Django 5.2.9 on 2025-12-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_chatmessage_notebookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='ingest_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdffile',
            name='is_ingested',
            field=models.BooleanField(default=False),
        ),
    ]
