# Generated by Django 5.2.9 on 2025-12-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_pdffile_ingest_error_pdffile_is_ingested'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='ingest_task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
