# Generated by GPT for schema compatibility on 2026-01-02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0007_activitylog"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
DO $$
BEGIN
    -- If a dedup unique constraint exists from a previously applied branch, drop it.
    -- (Safe no-op if it doesn't exist.)
    BEGIN
        ALTER TABLE files_pdffile DROP CONSTRAINT IF EXISTS uniq_user_content_sha256;
    EXCEPTION WHEN undefined_table THEN
        -- Table doesn't exist yet, ignore.
        NULL;
    END;

    -- If the column exists and is NOT NULL, relax it so older code that doesn't set it can insert.
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_name = 'files_pdffile'
          AND column_name = 'content_sha256'
    ) THEN
        BEGIN
            ALTER TABLE files_pdffile ALTER COLUMN content_sha256 DROP NOT NULL;
        EXCEPTION WHEN others THEN
            -- Ignore if already nullable or other benign states.
            NULL;
        END;
    END IF;
END $$;
""",
            reverse_sql=migrations.RunSQL.noop,
        )
    ]


